### ISSUE TITLE
  ubuntu20.04 GPD Installation Issue

### ISSUE THREAD

**Issue by EliKinova** [NunoDuarte/3DSGrasp#4]
May I ask which version of GPD was installed in ubuntu20.04 and what dependencies are required? I want to know the versions of PCL, Eigen and OpenCV.

**Comment by NunoDuarte** [comment]
Hi, I'm really sorry for the delay. The GPD version is the most recent one but I did make a fork to make some changes to work on Ubuntu 20.04 and for our purpose. You can have a look: https://github.com/NunoDuarte/gpd 

As for the versions: PCL - 1.11; Eigen - 3.37; opencv - 4.5.5

**Comment by NunoDuarte** [comment]
Closed due to inactivity
